-- OWOT world/tile storage (PostgreSQL). Separate from accounts and other PG databases.
-- Safe to apply only to the dedicated owot_worlds database.

CREATE TABLE IF NOT EXISTS world (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    owner_id integer,
    created_at bigint NOT NULL,
    feature_go_to_coord integer NOT NULL DEFAULT 0,
    feature_membertiles_addremove boolean NOT NULL DEFAULT false,
    feature_paste integer NOT NULL DEFAULT 0,
    feature_coord_link integer NOT NULL DEFAULT 0,
    feature_url_link integer NOT NULL DEFAULT 0,
    custom_bg text NOT NULL DEFAULT '',
    custom_cursor text NOT NULL DEFAULT '',
    custom_guest_cursor text NOT NULL DEFAULT '',
    custom_color text NOT NULL DEFAULT '',
    custom_tile_owner text NOT NULL DEFAULT '',
    custom_tile_member text NOT NULL DEFAULT '',
    writability integer NOT NULL DEFAULT 0,
    readability integer NOT NULL DEFAULT 0,
    properties text NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS tile (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id integer NOT NULL REFERENCES world (id) ON DELETE CASCADE,
    content varchar(128) NOT NULL,
    "tileY" integer NOT NULL,
    "tileX" integer NOT NULL,
    properties text NOT NULL DEFAULT '{}',
    writability integer,
    created_at bigint NOT NULL,
    UNIQUE (world_id, "tileY", "tileX")
);

CREATE TABLE IF NOT EXISTS whitelist (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    world_id integer NOT NULL REFERENCES world (id) ON DELETE CASCADE,
    created_at bigint NOT NULL,
    UNIQUE (user_id, world_id)
);

CREATE INDEX IF NOT EXISTS tile_world_id ON tile (world_id);
CREATE INDEX IF NOT EXISTS tile_world_pos ON tile (world_id, "tileY", "tileX");
CREATE INDEX IF NOT EXISTS whitelist_world_id ON whitelist (world_id);
CREATE INDEX IF NOT EXISTS whitelist_user_id ON whitelist (user_id);
CREATE INDEX IF NOT EXISTS world_owner_id ON world (owner_id);
